// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yedpzredlfafvabxumba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZHB6cmVkbGZhZnZhYnh1bWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDk5MDksImV4cCI6MjA2MjYyNTkwOX0.Fgm038M7QXGraGtudALvhTmpCLjCZkrgV7p9M0xoorY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);